services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: news-aggregator-app
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: news-aggregator-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

    redis:
        image: redis:alpine
        container_name: news-aggregator-redis
        ports:
            - "6379:6379"
        networks:
            - laravel

volumes:
    dbdata:

networks:
    laravel:
        driver: bridge
